# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.4/metricbeat-module-kibana.html

- module: kibana
  xpack.enabled: true
  period: 10s
  hosts: ["http://kibana:5601"]
  username: "elastic"
  password: "admin"
