# Module: logstash
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.4/metricbeat-module-logstash.html

- module: logstash
  metricsets:
    - node
    - node_stats
  xpack.enabled: true
  period: 10s
  hosts: ["http://logstash:9600"]
  username: "elastic"
  password: "admin"
