# https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml
###################### Metricbeat Configuration Example #######################
# =========================== Modules configuration ============================
network.host: 0.0.0.0

metricbeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: true
  
  # Period on which files under path should be checked for changes
  reload.period: 10s

  name: metricbeat

  tags: ["monitoring"]

#-------------------------------- Autodiscovery -------------------------------
# Autodiscover allows you to detect changes in the system and spawn new modules as they happen.
# metricbeat.autodiscover:
#   providers:
#     - type: docker
#       # https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
#       hints.enabled: true

metricbeat.modules:
#------------------------------- System Module -------------------------------
- module: system
  metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime

#------------------------------- Docker Module -------------------------------
# - module: docker
#   metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
#   hosts: ["unix:///var/run/docker.sock"]
#   period: 10s

#---------------------------- Elasticsearch Module ---------------------------
# - module: elasticsearch
#   xpack-enabled: true
#   metricsets:
#     - node
#     - node_stats
#     #- index
#     #- index_recovery
#     #- index_summary
#     #- shard
#     #- ml_job
#   period: 10s
#   hosts: ["http://elasticsearch:9200"]
#   username: "elastic"
#   password: "admin"
#================================ Processors ===================================
# processors:
# - add_cloud_metadata: ~
# - add_docker_metadata: ~
# - add_locale:
#     format: offset
# - add_host_metadata:
#     netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "admin"

#============================== Dashboards =====================================
setup.dashboards.enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: 'http://kibana:5601'
  username: 'elastic'
  password: 'admin'

#============================== Logging =========================================
logging.level: debug
logging.selectors: ["*"]


#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch:
