# Kali
FROM kalilinux/kali-last-release as kali
RUN apt update -y
RUN apt install -y \ 
        mc          curl        iptables    inetutils-ping \    
        net-tools   procps      vim         openjdk-11-jre-headless \
        ssh         tcpdump     nmap        openvpn \
RUN apt install -y python3 metasploit-framework
ADD https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py /bin/systemctl
RUN chmod +x /bin/systemctl
WORKDIR /
# Copy over PE-related files
COPY ./Attacks/Privilege_Escalation/dirtypipe.sh ./Attacks/Privilege_Escalation/CVE-2022-0847.c ./
