# ============================== Filebeat inputs ===============================

filebeat.inputs:

# For access log
- type: log
  enabled: true
  paths:
    - /var/log/apache2/access.log
  tags: ["apache"]

# For syslog
- type: log
  enabled: true
  paths:
    - /var/log/syslog
  tags: ["syslog"]

# For auth.log
- type: log
  enabled: true
  paths:
    - /var/log/auth.log
  tags: ["auth"]

# For btmp
- type: log
  enabled: true
  paths:
    - /var/log/btmp
  tags: ["faillog"]

# For wtmp
- type: log
  enabled: true
  paths:
    - /var/log/wtmp
  tags: ["lastlog"]

# For ProFTPD
- type: log
  enabled: true
  paths:
    - /var/log/proftpd/xferlog
    - /var/log/proftpd/proftpd.log
  tags: ["proftpd"]

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # IP of Logstash
  hosts: ["192.168.1.201:5044"]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
