heartbeat.monitors:
- type: http
  name: Elastic Web Service Status
  schedule: '@every 10s'
  urls:
    - http://elasticsearch:9200
  check.response.status: [200]

- type: http
  name: Kibana Web Service Status
  schedule: '@every 10s'
  urls:
    - http://kibana:5601

- type: http
  name: SuiteCRM Web Service
  schedule: '@every 10s'
  max_redirects: 2
  urls:
    - http://192.168.1.201:8888
  check.response.status: [200]

- type: icmp
  name: Elastic Server Alive Status
  schedule: '@every 5s'
  hosts:
    - elasticsearch

- type: icmp
  name: Kibana Server Alive Status
  schedule: '@every 5s'
  hosts:
    - kibana
    
- type: icmp
  name: Logstash Server Alive Status
  schedule: '@every 5s'
  hosts:
    - logstash
    
- type: icmp
  name: ELK Router Server Alive Status
  schedule: '@every 5s'
  hosts:
    - r3

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "http"
  username: 'elastic'
  password: 'admin'
