
# https://www.docker.elastic.co/

FROM docker.elastic.co/elasticsearch/elasticsearch:8.4.3

FROM docker.elastic.co/logstash/logstash:8.4.3

FROM docker.elastic.co/kibana/kibana:8.4.3

# Add your plugins setup here
# Example: RUN kibana-plugin install <name|url>
